<?php
return array(
	'site_name'=>array(
		'title'=>'站点名称:',
		'type'=>'text',
		'tip'=>'填写你的站点名称',
		'value'=>'',
	),
	'site_url'=>array(
		'title'=>'站点url:',
		'type'=>'text',
		'tip'=>'填写你的站点互联网完整地址，带http或https',
		'value'=>'',
	),
	'update_url'=>array(
		'title'=>'文章访问地址:',
		'type'=>'text',
		'tip'=>'应如这个格式article/index@www.molibei.com,记得@自己的域名（不带http协议）',
		'value'=>'',
	),
	'update_rss'=>array(
		'title'=>'文章rss地址:',
		'type'=>'text',
		'tip'=>'应如这个格式article/rss@www.molibei.com,记得@自己的域名（不带http协议）',
		'value'=>'',
	),
);
